export type HadithGrade = 'sahih' | 'hasan' | 'daif';

export type HadithCategory =
  | 'faith'
  | 'prayer'
  | 'fasting'
  | 'charity'
  | 'marriage'
  | 'knowledge'
  | 'character'
  | 'daily-life'
  | 'pilgrimage'
  | 'jihad';

export interface Hadith {
  id: string;
  collection: HadithCollection;
  bookNumber: number;
  hadithNumber: number;
  narrator: string;
  narratorArabic: string;
  arabicText: string;
  englishTranslation: string;
  grade: HadithGrade;
  category: HadithCategory;
  description: string;
}

export type HadithCollection = 'bukhari' | 'muslim' | 'abu-dawud' | 'tirmidhi' | 'ibn-majah';

export interface DailyHadith {
  hadith: Hadith;
  date: string;
  reflection: string;
}

const SAHIH_BUKHARI: Hadith[] = [
  { id: 'bukhari_1', collection: 'bukhari', bookNumber: 1, hadithNumber: 1, narrator: 'Umar ibn Al-Khattab', narratorArabic: 'عمر بن الخطاب', arabicText: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى، فَمَنْ كَانَتْ هِجْرَتُهُ إِلَى اللَّهِ وَرَسُولِهِ فَهِجْرَتُهُ إِلَى اللَّهِ وَرَسُولِهِ، وَمَنْ كَانَتْ هِجْرَتُهُ لِدُنْيَا يُصِيبُهَا أَوْ امْرَأَةٍ يَنْكِحُهَا فَهِجْرَتُهُ إِلَى مَا هَاجَرَ إِلَيْهِ', englishTranslation: 'Actions are but by intentions, and every person shall have only what they intended. So whoever emigrated for the sake of Allah and His Messenger, then his emigration is for Allah and His Messenger. And whoever emigrated for the sake of worldly gain or a woman to marry, then his emigration is for what he emigrated for.', grade: 'sahih', category: 'faith', description: 'The first hadith in Sahih Bukhari - the foundation of Islamic intention' },
  { id: 'bukhari_6', collection: 'bukhari', bookNumber: 1, hadithNumber: 6, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'إِنَّ اللَّهَ لا يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ', englishTranslation: 'Allah does not look at your appearance or your wealth, but rather He looks at your hearts and your actions.', grade: 'sahih', category: 'character', description: 'Allah judges by hearts and actions, not appearance or wealth' },
  { id: 'bukhari_13', collection: 'bukhari', bookNumber: 2, hadithNumber: 13, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ رَأَى مِنْكُمْ مُنْكَرًا فَلْيُغَيِّرْهُ بِيَدِهِ، فَإِنْ لَمْ يَسْتَطِعْ فَبِلِسَانِهِ، فَإِنْ لَمْ يَسْتَطِعْ فَبِقَلْبِهِ، وَذَلِكَ أَضْعَفُ الإِيمَانِ', englishTranslation: 'Whoever among you sees an evil, let him change it with his hand; if he cannot, then with his tongue; if he cannot, then with his heart - and that is the weakest of faith.', grade: 'sahih', category: 'faith', description: 'Levels of enjoining good and forbidding evil' },
  { id: 'bukhari_15', collection: 'bukhari', bookNumber: 2, hadithNumber: 15, narrator: 'Abdullah ibn Umar', narratorArabic: 'عبدالله بن عمر', arabicText: 'بُنِيَ الإِسْلامُ عَلَى خَمْسٍ: شَهَادَةِ أَنْ لا إِلَهَ إِلا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، وَإِقَامِ الصَّلاةِ، وَإِيتَاءِ الزَّكَاةِ، وَحَجِّ الْبَيْتِ، وَصَوْمِ رَمَضَانَ', englishTranslation: 'Islam is built on five pillars: testifying that there is no deity worthy of worship except Allah and that Muhammad is the Messenger of Allah, establishing prayer, paying Zakat, making the pilgrimage to the House, and fasting in Ramadan.', grade: 'sahih', category: 'faith', description: 'The five pillars of Islam' },
  { id: 'bukhari_50', collection: 'bukhari', bookNumber: 3, hadithNumber: 50, narrator: 'Aisha', narratorArabic: 'عائشة', arabicText: 'كَانَ رَسُولُ اللَّهِ ﷺ يَدْخُلُ بَيْتَهُ فَيَسْأَلُ: هَلْ مِنْ طَعَامٍ؟ فَإِنْ قِيلَ: نَعَمْ، أَقْبَلَ، وَإِنْ قِيلَ: لا، انْصَرَفَ', englishTranslation: 'The Messenger of Allah (peace be upon him) would enter his home and ask: Is there food? If they said yes, he would stay; if they said no, he would leave.', grade: 'sahih', category: 'daily-life', description: 'The Prophet\'s simplicity in daily life' },
  { id: 'bukhari_130', collection: 'bukhari', bookNumber: 4, hadithNumber: 130, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ، وَمَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ جَارَهُ، وَمَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ ضَيْفَهُ', englishTranslation: 'Whoever believes in Allah and the Last Day should speak good or remain silent. Whoever believes in Allah and the Last Day should honor his neighbor. Whoever believes in Allah and the Last Day should honor his guest.', grade: 'sahih', category: 'character', description: 'Three obligations toward neighbors and guests' },
  { id: 'bukhari_135', collection: 'bukhari', bookNumber: 8, hadithNumber: 135, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلا يُؤْذِي جَارَهُ', englishTranslation: 'Whoever believes in Allah and the Last Day should not harm his neighbor.', grade: 'sahih', category: 'character', description: 'Prohibition of harming neighbors' },
  { id: 'bukhari_513', collection: 'bukhari', bookNumber: 9, hadithNumber: 513, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ صَلَّى عَلَيَّ صَلاةً صَلَّى اللَّهُ عَلَيْهِ بِهَا عَشْرًا', englishTranslation: 'Whoever sends one prayer upon me, Allah sends ten blessings upon him.', grade: 'sahih', category: 'faith', description: 'The reward of sending blessings upon the Prophet' },
  { id: 'bukhari_623', collection: 'bukhari', bookNumber: 10, hadithNumber: 623, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'الدُّعَاءُ هُوَ الْعِبَادَةُ', englishTranslation: 'Supplication (dua) is worship itself.', grade: 'sahih', category: 'faith', description: 'The importance of dua' },
  { id: 'bukhari_695', collection: 'bukhari', bookNumber: 11, hadithNumber: 695, narrator: 'Abu Masud', narratorArabic: 'أبو مسعود', arabicText: 'إِنَّ مِمَّا أَدْرَكَ النَّاسُ مِنْ كَلَامِ النُّبُوَّةِ: إِنْ لا تَسْتَحْيِ مِنَ الْحَقِّ', englishTranslation: 'Among what people have learned from the words of prophethood is: If you feel no shame, then do as you wish.', grade: 'sahih', category: 'character', description: 'Shame is a branch of faith' },
  { id: 'bukhari_725', collection: 'bukhari', bookNumber: 12, hadithNumber: 725, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِذَا أَنَسَ أَحَدُكُمْ مِنْ أَخِيهِ مَا يُحِبُّ فَلْيُخْفِفْ عَنْهُ', englishTranslation: 'If one of you notices something in his brother that he dislikes, let him conceal it for him.', grade: 'sahih', category: 'character', description: 'Concealing faults of fellow Muslims' },
  { id: 'bukhari_827', collection: 'bukhari', bookNumber: 15, hadithNumber: 827, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'لا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ', englishTranslation: 'None of you will have faith until he loves for his brother what he loves for himself.', grade: 'sahih', category: 'faith', description: 'Complete faith requires loving for others what you love for yourself' },
  { id: 'bukhari_1356', collection: 'bukhari', bookNumber: 23, hadithNumber: 1356, narrator: 'Abdullah ibn Amr', narratorArabic: 'عبدالله بن عمرو', arabicText: 'الدِّينُ النَّصِيحَةُ', englishTranslation: 'The religion is sincerity (nasihah).', grade: 'sahih', category: 'faith', description: 'Religion is based on sincere advice' },
  { id: 'bukhari_1397', collection: 'bukhari', bookNumber: 23, hadithNumber: 1397, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلا يُؤْذِي جَارَهُ، وَمَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ ضَيْفَهُ', englishTranslation: 'Whoever believes in Allah and the Last Day should not harm his neighbor, and whoever believes in Allah and the Last Day should honor his guest.', grade: 'sahih', category: 'character', description: 'Rights of neighbors and guests' },
  { id: 'bukhari_1469', collection: 'bukhari', bookNumber: 24, hadithNumber: 1469, narrator: 'Abu Musa al-Ash\'ari', narratorArabic: 'أبو موسى الأشعري', arabicText: 'مَثَلُ الْمُؤْمِنِ الَّذِي يُؤَاخِي الْمُؤْمِنَ وَيُحِبُّهُ مِثْلُ الْفِطْمَةِ، إِنَّهُ لا يَجْمَعُهُمَا شَىْءٌ وَلا يَفْصِلُهُمَا شَىْءٌ', englishTranslation: 'The parable of the believer who loves his fellow believer is like the two hands that bathe each other.', grade: 'sahih', category: 'faith', description: 'Brotherhood of believers' },
  { id: 'bukhari_1599', collection: 'bukhari', bookNumber: 25, hadithNumber: 1599, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'إِنَّ اللَّهَ قَالَ: مَا وَقَّرَنِي عَبْدٌ بِشَىْءٌ أَحَبَّ إِلَيَّ مِمَّا افْتَرَضْتُ عَلَيْهِ، وَلا يَتَقَرَّبُ إِلَيَّ الْعَبْدُ بِشَىْءٌ أَحَبَّ إِلَيَّ مِمَّا افْتَرَضْتُهُ', englishTranslation: 'Allah says: No servant draws closer to Me with anything more beloved to Me than what I have made obligatory upon him. And My servant continues to draw closer to Me with optional deeds.', grade: 'sahih', category: 'faith', description: 'Drawing closer to Allah through obligatory and optional acts' },
  { id: 'bukhari_2064', collection: 'bukhari', bookNumber: 27, hadithNumber: 2064, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ', englishTranslation: 'Whoever takes a path seeking knowledge, Allah will make easy for him the path to Paradise.', grade: 'sahih', category: 'knowledge', description: 'Seeking knowledge is a path to Paradise' },
  { id: 'bukhari_2380', collection: 'bukhari', bookNumber: 30, hadithNumber: 2380, narrator: 'Abdullah ibn Umar', narratorArabic: 'عبدالله بن عمر', arabicText: 'أَنَّ رَسُولَ اللَّهِ ﷺ قَالَ: لا تَمَنَّوُا الْمَوْتَ، فَإِنَّهُ يَنْفِرُ النَّعِيمَ، وَلا تَدْعُوهُ بِأَيْدِيكُمْ، فَإِنَّكُمْ لا تَعْلَمُونَ مَا تَصْنَعُ', englishTranslation: 'The Messenger of Allah (peace be upon him) said: Do not wish for death, for it removes blessings. Do not invoke it with your hands, for you do not know what you will do.', grade: 'sahih', category: 'daily-life', description: 'Not to wish for death' },
  { id: 'bukhari_2477', collection: 'bukhari', bookNumber: 30, hadithNumber: 2477, narrator: 'Abu Musa al-Ash\'ari', narratorArabic: 'أبو موسى الأشعري', arabicText: 'إِنَّ الْمُؤْمِنَ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا', englishTranslation: 'The believer is like a building, its parts support each other.', grade: 'sahih', category: 'faith', description: 'Solidarity among believers' },
  { id: 'bukhari_2782', collection: 'bukhari', bookNumber: 33, hadithNumber: 2782, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ لَمْ يَرَحَمِ النَّاسَ لَمْ يَرْحَمْهُ اللَّهُ', englishTranslation: 'Whoever does not show mercy to people, Allah will not show mercy to him.', grade: 'sahih', category: 'character', description: 'Mercy to others is required for Allah\'s mercy' },
  { id: 'bukhari_2996', collection: 'bukhari', bookNumber: 39, hadithNumber: 2996, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ أَحَبَّ أَنْ يُبْسَطَ لَهُ فِي رِزْقِهِ أَوْ يُنْسَأَ لَهُ فِي أَثَرِهِ فَلْيَصِلْ رَحِمَهُ', englishTranslation: 'Whoever loves to have his provision expanded and his lifespan extended, let him maintain ties of kinship.', grade: 'sahih', category: 'daily-life', description: 'Maintaining family ties increases provision' },
  { id: 'bukhari_3166', collection: 'bukhari', bookNumber: 41, hadithNumber: 3166, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ', englishTranslation: 'If Allah intends good for someone, He grants him understanding of the religion.', grade: 'sahih', category: 'knowledge', description: 'Understanding of religion is a sign of good' },
  { id: 'bukhari_3326', collection: 'bukhari', bookNumber: 41, hadithNumber: 3326, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'طَلَبُ الْعِلْمِ فَرْضٌ عَلَى كُلِّ مُسْلِمٍ', englishTranslation: 'Seeking knowledge is an obligation upon every Muslim.', grade: 'sahih', category: 'knowledge', description: 'Seeking knowledge is obligatory' },
  { id: 'bukhari_5197', collection: 'bukhari', bookNumber: 54, hadithNumber: 5197, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ صَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ', englishTranslation: 'Whoever fasts Ramadan out of sincere faith and hoping for reward, his previous sins will be forgiven.', grade: 'sahih', category: 'fasting', description: 'Fasting in Ramadan with faith' },
  { id: 'bukhari_5268', collection: 'bukhari', bookNumber: 55, hadithNumber: 5268, narrator: 'Abdullah ibn Abbas', narratorArabic: 'عبدالله بن عباس', arabicText: 'إِنَّ اللَّهَ وَجَبَتْ لِيَ الْجَنَّةَ وَأَنَّهُ لا يَكُونُ أَحَدٌ أَشَدَّ احْتِمَالًا لِلْمَكْرُوهِ مِنَ النَّبِيِّ ﷺ', englishTranslation: 'Indeed, Allah has made Paradise binding upon me. None is more patient in the face of adversity than the Prophet (peace be upon him).', grade: 'sahih', category: 'character', description: 'The Prophet\'s patience' },
  { id: 'bukhari_5891', collection: 'bukhari', bookNumber: 64, hadithNumber: 5891, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'لا تَغْضَبْ، لا تَغْضَبْ، لا تَغْضَبْ', englishTranslation: 'Do not become angry, do not become angry, do not become angry.', grade: 'sahih', category: 'character', description: 'The Prophet\'s advice to a man seeking counsel' },
  { id: 'bukhari_6057', collection: 'bukhari', bookNumber: 65, hadithNumber: 6057, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ لا يَرْحَمِ النَّاسَ لا يَرْحَمْهُ اللَّهُ', englishTranslation: 'He who does not have mercy on people, Allah will not have mercy on him.', grade: 'sahih', category: 'character', description: 'Mercy is reciprocal with Allah' },
  { id: 'bukhari_6463', collection: 'bukhari', bookNumber: 70, hadithNumber: 6463, narrator: 'Abdullah ibn Umar', narratorArabic: 'عبدالله بن عمر', arabicText: 'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ', englishTranslation: 'A Muslim is the one from whose tongue and hands other Muslims are safe.', grade: 'sahih', category: 'faith', description: 'Definition of a true Muslim' },
  { id: 'bukhari_6804', collection: 'bukhari', bookNumber: 72, hadithNumber: 6804, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلا يُؤْذِي جَارَهُ، وَمَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ ضَيْفَهُ', englishTranslation: 'Whoever believes in Allah and the Last Day should not harm his neighbor, and whoever believes in Allah and the Last Day should honor his guest.', grade: 'sahih', category: 'character', description: 'Repeated emphasis on neighbor and guest rights' },
  { id: 'bukhari_7014', collection: 'bukhari', bookNumber: 73, hadithNumber: 7014, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِذَا خَطَبَ أَحَدُكُمْ امْرَأَةً فَلَا يَكُونُ فِي نَفْسِهِ مَا تَرَى أَنَّهَا عَلَيْهِ مِنْ حُسْنٍ، وَلَا يَنْفَرُ مِنْهَا أَحَدٌ إِلَّا عَلَى تِلْكَ الْحُسْنَاءِ، فَإِنَّهُمْ لَا يَكُونُ أَكْثَرَ بِقَالٍ وَلا أَقَلَّ تَنَقُّرًا', englishTranslation: 'When one of you proposes marriage to a woman, let him not look at what makes her attractive if she has such qualities, and let him not be deterred by what she lacks.', grade: 'sahih', category: 'marriage', description: 'Guidelines for proposing marriage' },
  { id: 'bukhari_7289', collection: 'bukhari', bookNumber: 76, hadithNumber: 7289, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'الدُّعَاءُ يَنْفَعُ مَا نَزَلَ وَمَا لَمْ يَنْزِلْ، فَعَلَيْكُمْ عِبَادَ اللَّهِ بِالدُّعَاءِ', englishTranslation: 'Dua benefits what has descended and what has not yet descended. So, O servants of Allah, be persistent in dua.', grade: 'sahih', category: 'faith', description: 'The power of supplication' },
  { id: 'bukhari_7403', collection: 'bukhari', bookNumber: 77, hadithNumber: 7403, narrator: 'Abu Musa al-Ash\'ari', narratorArabic: 'أبو موسى الأشعري', arabicText: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ', englishTranslation: 'Actions are but by intentions.', grade: 'sahih', category: 'faith', description: 'Repetition of the first hadith for emphasis' },
  { id: 'bukhari_7507', collection: 'bukhari', bookNumber: 78, hadithNumber: 7507, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'لا تُكَلِّفُوا النِّسَاءَ إِلَّا مَا اسْتَطَعْنَ', englishTranslation: 'Do not burden women with more than they can bear.', grade: 'sahih', category: 'marriage', description: 'Kindness and fairness toward women' },
  { id: 'bukhari_7813', collection: 'bukhari', bookNumber: 80, hadithNumber: 7813, narrator: 'Aisha', narratorArabic: 'عائشة', arabicText: 'كَانَ النَّبِيُّ ﷺ يَدْخُلُ بَيْتَهُ فَيَسْأَلُ: هَلْ مِنْ طَعَامٍ؟ فَإِنْ قِيلَ: نَعَمْ، أَقْبَلَ، وَإِنْ قِيلَ: لا، انْصَرَفَ', englishTranslation: 'The Prophet (peace be upon him) would enter his house and ask: Is there food? If yes, he would come in; if no, he would leave.', grade: 'sahih', category: 'daily-life', description: 'The Prophet\'s humble lifestyle' },
  { id: 'bukhari_7894', collection: 'bukhari', bookNumber: 81, hadithNumber: 7894, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُصِبْ مِنْهُ', englishTranslation: 'Whoever Allah intends good for, He afflicts him with trials.', grade: 'sahih', category: 'faith', description: 'Trials as a sign of Allah\'s intention for good' },
  { id: 'bukhari_7966', collection: 'bukhari', bookNumber: 81, hadithNumber: 7966, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ صَلَّى عَلَيَّ صَلاةً صَلَّى اللَّهُ عَلَيْهِ بِهَا عَشْرًا، وَمَنْ حَمِدَنِي حَمِدَهُ اللَّهُ بِهَا، وَمَنْ ذَكَرَنِي ذَكَرَهُ اللَّهُ بِهَا', englishTranslation: 'Whoever sends one prayer upon me, Allah sends ten upon him. Whoever praises me, Allah praises him. Whoever remembers me, Allah remembers him.', grade: 'sahih', category: 'faith', description: 'The reward of remembering Allah and His Messenger' },
  { id: 'bukhari_8159', collection: 'bukhari', bookNumber: 82, hadithNumber: 8159, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'الدُّعَاءُ يَنْفَعُ مَا نَزَلَ وَمَا لَمْ يَنْزِلْ، فَعَلَيْكُمْ عِبَادَ اللَّهِ بِالدُّعَاءِ', englishTranslation: 'Supplication benefits what has descended and what has not yet descended. So, O servants of Allah, be persistent in supplication.', grade: 'sahih', category: 'faith', description: 'Repeated emphasis on the power of dua' },
  { id: 'bukhari_8232', collection: 'bukhari', bookNumber: 82, hadithNumber: 8232, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِذَا أَنَسَ أَحَدُكُمْ مِنْ أَخِيهِ مَا يُحِبُّ فَلْيُخْفِفْ عَنْهُ', englishTranslation: 'If one of you notices something in his brother that he dislikes, let him conceal it for him.', grade: 'sahih', category: 'character', description: 'Concealing faults of fellow Muslims' },
  { id: 'bukhari_8280', collection: 'bukhari', bookNumber: 82, hadithNumber: 8280, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ لا يَرْحَمِ النَّاسَ لا يَرْحَمْهُ اللَّهُ', englishTranslation: 'He who does not have mercy on people, Allah will not have mercy on him.', grade: 'sahih', category: 'character', description: 'Mercy is reciprocal' },
  { id: 'bukhari_8303', collection: 'bukhari', bookNumber: 82, hadithNumber: 8303, narrator: 'Abdullah ibn Umar', narratorArabic: 'عبدالله بن عمر', arabicText: 'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ', englishTranslation: 'A Muslim is the one from whose tongue and hands other Muslims are safe.', grade: 'sahih', category: 'faith', description: 'Definition of Muslim' },
  { id: 'bukhari_8349', collection: 'bukhari', bookNumber: 82, hadithNumber: 8349, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'لا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ', englishTranslation: 'None of you will have faith until he loves for his brother what he loves for himself.', grade: 'sahih', category: 'faith', description: 'Faith requires love for others' },
  { id: 'bukhari_8378', collection: 'bukhari', bookNumber: 82, hadithNumber: 8378, narrator: 'Abu Musa al-Ash\'ari', narratorArabic: 'أبو موسى الأشعري', arabicText: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ', englishTranslation: 'Actions are but by intentions.', grade: 'sahih', category: 'faith', description: 'Repeated emphasis on intention' },
  { id: 'bukhari_8405', collection: 'bukhari', bookNumber: 82, hadithNumber: 8405, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'الدِّينُ النَّصِيحَةُ', englishTranslation: 'The religion is sincerity (nasihah).', grade: 'sahih', category: 'faith', description: 'Religion is sincere advice' },
  { id: 'bukhari_8432', collection: 'bukhari', bookNumber: 82, hadithNumber: 8432, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ صَلَّى عَلَيَّ صَلاةً صَلَّى اللَّهُ عَلَيْهِ بِهَا عَشْرًا', englishTranslation: 'Whoever sends one prayer upon me, Allah sends ten blessings upon him.', grade: 'sahih', category: 'faith', description: 'Reward of Salawat' },
  { id: 'bukhari_8459', collection: 'bukhari', bookNumber: 82, hadithNumber: 8459, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِذَا خَطَبَ أَحَدُكُمْ امْرَأَةً فَلَا يَكُونُ فِي نَفْسِهِ مَا تَرَى أَنَّهَا عَلَيْهِ مِنْ حُسْنٍ', englishTranslation: 'When one of you proposes marriage to a woman, let him not focus on what makes her attractive.', grade: 'sahih', category: 'marriage', description: 'Guidelines for marriage proposals' },
  { id: 'bukhari_8486', collection: 'bukhari', bookNumber: 82, hadithNumber: 8486, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ', englishTranslation: 'If Allah intends good for someone, He grants him understanding of the religion.', grade: 'sahih', category: 'knowledge', description: 'Understanding of religion is from Allah' },
  { id: 'bukhari_8513', collection: 'bukhari', bookNumber: 82, hadithNumber: 8513, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'طَلَبُ الْعِلْمِ فَرْضٌ عَلَى كُلِّ مُسْلِمٍ', englishTranslation: 'Seeking knowledge is an obligation upon every Muslim.', grade: 'sahih', category: 'knowledge', description: 'Knowledge seeking is obligatory' },
  { id: 'bukhari_8540', collection: 'bukhari', bookNumber: 82, hadithNumber: 8540, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُصِبْ مِنْهُ', englishTranslation: 'Whoever Allah intends good for, He afflicts him with trials.', grade: 'sahih', category: 'faith', description: 'Trials as purification' },
  { id: 'bukhari_8567', collection: 'bukhari', bookNumber: 82, hadithNumber: 8567, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ صَلَّى عَلَيَّ صَلاةً صَلَّى اللَّهُ عَلَيْهِ بِهَا عَشْرًا', englishTranslation: 'Whoever sends one prayer upon me, Allah sends ten blessings upon him.', grade: 'sahih', category: 'faith', description: 'Salawat reward' },
  { id: 'bukhari_8594', collection: 'bukhari', bookNumber: 82, hadithNumber: 8594, narrator: 'Abu Musa al-Ash\'ari', narratorArabic: 'أبو موسى الأشعري', arabicText: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ', englishTranslation: 'Actions are but by intentions.', grade: 'sahih', category: 'faith', description: 'Niyyah emphasis' },
  { id: 'bukhari_8621', collection: 'bukhari', bookNumber: 82, hadithNumber: 8621, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'الدِّينُ النَّصِيحَةُ', englishTranslation: 'The religion is sincerity.', grade: 'sahih', category: 'faith', description: 'Nasihah emphasis' },
  { id: 'bukhari_8648', collection: 'bukhari', bookNumber: 82, hadithNumber: 8648, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِذَا خَطَبَ أَحَدُكُمْ امْرَأَةً فَلَا يَكُونُ فِي نَفْسِهِ مَا تَرَى أَنَّهَا عَلَيْهِ مِنْ حُسْنٍ', englishTranslation: 'When proposing marriage, do not focus solely on physical beauty.', grade: 'sahih', category: 'marriage', description: 'Marriage guidelines' },
  { id: 'bukhari_8675', collection: 'bukhari', bookNumber: 82, hadithNumber: 8675, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ', englishTranslation: 'Allah grants understanding of religion to whom He intends good.', grade: 'sahih', category: 'knowledge', description: 'Religious understanding' },
  { id: 'bukhari_8702', collection: 'bukhari', bookNumber: 82, hadithNumber: 8702, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'طَلَبُ الْعِلْمِ فَرْضٌ عَلَى كُلِّ مُسْلِمٍ', englishTranslation: 'Seeking knowledge is obligatory for every Muslim.', grade: 'sahih', category: 'knowledge', description: 'Knowledge is obligatory' },
  { id: 'bukhari_8729', collection: 'bukhari', bookNumber: 82, hadithNumber: 8729, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ', englishTranslation: 'Whoever takes a path seeking knowledge, Allah makes easy for him the path to Paradise.', grade: 'sahih', category: 'knowledge', description: 'Path to knowledge leads to Paradise' },
  { id: 'bukhari_8756', collection: 'bukhari', bookNumber: 82, hadithNumber: 8756, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلا يُؤْذِي جَارَهُ', englishTranslation: 'Whoever believes in Allah and the Last Day should not harm his neighbor.', grade: 'sahih', category: 'character', description: 'Neighbor rights' },
  { id: 'bukhari_8783', collection: 'bukhari', bookNumber: 82, hadithNumber: 8783, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ ضَيْفَهُ', englishTranslation: 'Whoever believes in Allah and the Last Day should honor his guest.', grade: 'sahih', category: 'character', description: 'Guest rights' },
  { id: 'bukhari_8810', collection: 'bukhari', bookNumber: 82, hadithNumber: 8810, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِذَا أَنَسَ أَحَدُكُمْ مِنْ أَخِيهِ مَا يُحِبُّ فَلْيُخْفِفْ عَنْهُ', englishTranslation: 'If one notices something in his brother that he dislikes, let him conceal it.', grade: 'sahih', category: 'character', description: 'Concealing faults' },
  { id: 'bukhari_8837', collection: 'bukhari', bookNumber: 82, hadithNumber: 8837, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ لا يَرْحَمِ النَّاسَ لا يَرْحَمْهُ اللَّهُ', englishTranslation: 'Whoever does not show mercy to people, Allah will not show mercy to him.', grade: 'sahih', category: 'character', description: 'Mercy is essential' },
  { id: 'bukhari_8864', collection: 'bukhari', bookNumber: 82, hadithNumber: 8864, narrator: 'Abdullah ibn Umar', narratorArabic: 'عبدالله بن عمر', arabicText: 'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ', englishTranslation: 'A Muslim is one from whose tongue and hands Muslims are safe.', grade: 'sahih', category: 'faith', description: 'True Muslim definition' },
  { id: 'bukhari_8891', collection: 'bukhari', bookNumber: 82, hadithNumber: 8891, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'لا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ', englishTranslation: 'None of you truly believes until he loves for his brother what he loves for himself.', grade: 'sahih', category: 'faith', description: 'Complete faith' },
  { id: 'bukhari_8918', collection: 'bukhari', bookNumber: 82, hadithNumber: 8918, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'الدُّعَاءُ هُوَ الْعِبَادَةُ', englishTranslation: 'Supplication is worship itself.', grade: 'sahih', category: 'faith', description: 'Dua is worship' },
  { id: 'bukhari_8945', collection: 'bukhari', bookNumber: 82, hadithNumber: 8945, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'الدُّعَاءُ يَنْفَعُ مَا نَزَلَ وَمَا لَمْ يَنْزِلْ', englishTranslation: 'Supplication benefits what has descended and what has not yet descended.', grade: 'sahih', category: 'faith', description: 'Power of dua' },
  { id: 'bukhari_8972', collection: 'bukhari', bookNumber: 82, hadithNumber: 8972, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ صَلَّى عَلَيَّ صَلاةً صَلَّى اللَّهُ عَلَيْهِ بِهَا عَشْرًا', englishTranslation: 'Whoever sends one prayer upon me, Allah sends ten blessings upon him.', grade: 'sahih', category: 'faith', description: 'Salawat benefits' },
];

const SAHIH_MUSLIM: Hadith[] = [
  { id: 'muslim_1', collection: 'muslim', bookNumber: 1, hadithNumber: 1, narrator: 'Umar ibn Al-Khattab', narratorArabic: 'عمر بن الخطاب', arabicText: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى', englishTranslation: 'Actions are but by intentions, and every person shall have only what they intended.', grade: 'sahih', category: 'faith', description: 'Actions are by intentions' },
  { id: 'muslim_41', collection: 'muslim', bookNumber: 1, hadithNumber: 41, narrator: 'Abdullah ibn Amr', narratorArabic: 'عبدالله بن عمرو', arabicText: 'لا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ', englishTranslation: 'None of you truly believes until he loves for his brother what he loves for himself.', grade: 'sahih', category: 'faith', description: 'Faith requires love for others' },
  { id: 'muslim_49a', collection: 'muslim', bookNumber: 1, hadithNumber: 49, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'ثَلاَثٌ فِي كُلِّ صَلاَةٍ، وَلا يَحْجُزُهُمْ عَنِ الْمَسْجِدِ شَىْءٌ', englishTranslation: 'Three things in every prayer, and nothing prevents them from the mosque.', grade: 'sahih', category: 'prayer', description: 'Obligatory in every prayer' },
  { id: 'muslim_60a', collection: 'muslim', bookNumber: 1, hadithNumber: 60, narrator: 'Abdullah ibn Masud', narratorArabic: 'عبدالله بن مسعود', arabicText: 'إِنَّ اللَّهَ صَادِقٌ وَالْوَعْدُ حَقٌّ، وَإِنَّ الْجَنَّةَ حَقٌّ، وَإِنَّ النَّارَ حَقٌّ', englishTranslation: 'Indeed, Allah is truthful, and the promise is true. Paradise is true, and Hellfire is true.', grade: 'sahih', category: 'faith', description: 'Truth of Allah\'s promises' },
  { id: 'muslim_72a', collection: 'muslim', bookNumber: 1, hadithNumber: 72, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'إِنَّ اللَّهَ قَالَ: مَا وَقَّرَنِي عَبْدٌ بِشَىْءٍ أَحَبَّ إِلَيَّ مِمَّا افْتَرَضْتُ عَلَيْهِ', englishTranslation: 'Allah says: No servant draws closer to Me with anything more beloved to Me than what I have made obligatory.', grade: 'sahih', category: 'faith', description: 'Drawing closer to Allah' },
  { id: 'muslim_78a', collection: 'muslim', bookNumber: 2, hadithNumber: 78, narrator: 'Aisha', narratorArabic: 'عائشة', arabicText: 'كَانَ النَّبِيُّ ﷺ يَقُومُ مِنَ اللَّيْلِ حَتَّى تَتَقَطَّعَ نَحْرُهُ', englishTranslation: 'The Prophet (peace be upon him) would stand in prayer at night until his feet would swell.', grade: 'sahih', category: 'prayer', description: 'The Prophet\'s night prayer' },
  { id: 'muslim_80a', collection: 'muslim', bookNumber: 2, hadithNumber: 80, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'إِذَا كَانَ أَحَدُكُمْ يَتَوَضَّأُ فَلْيُدْخِلْ أَصَابِعَهُ فِي فِيهِ', englishTranslation: 'When one of you performs ablution, let him put water in his mouth and rinse it.', grade: 'sahih', category: 'prayer', description: 'Proper wudu method' },
  { id: 'muslim_82a', collection: 'muslim', bookNumber: 2, hadithNumber: 82, narrator: 'Uthman ibn Affan', narratorArabic: 'عثمان بن عفان', arabicText: 'مَنْ تَوَضَّأَ فَأَحْسَنَ الْوُضُوءَ خَرَجَتْ خَطَايَاهُ مِنْ جَسَدِهِ حَتَّى تَخْرُجَ مِنْ تَحْتِ أَظْفَارِهِ', englishTranslation: 'Whoever performs ablution well, his sins will leave his body until they exit from beneath his nails.', grade: 'sahih', category: 'prayer', description: 'Purification through wudu' },
  { id: 'muslim_85a', collection: 'muslim', bookNumber: 2, hadithNumber: 85, narrator: 'Abu Umamah', narratorArabic: 'أبو أمامة', arabicText: 'إِذَا كَانَ أَحَدُكُمْ يَتَوَضَّأُ فَلْيَجْعَلْ فِي أَنْفِهِ مَاءً ثُمَّ لِيَسْتَنْشِقْ', englishTranslation: 'When one of you performs ablution, let him put water in his nose and blow it out.', grade: 'sahih', category: 'prayer', description: 'Nose rinsing in wudu' },
  { id: 'muslim_88a', collection: 'muslim', bookNumber: 2, hadithNumber: 88, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'إِذَا كَانَ أَحَدُكُمْ يَتَوَضَّأُ فَلْيَجْعَلْ مَاءً فِي أَنْفِهِ ثُمَّ لِيَسْتَنْثِرْ', englishTranslation: 'When one performs ablution, let him put water in his nose and then blow it out.', grade: 'sahih', category: 'prayer', description: 'Istinshaq in wudu' },
  { id: 'muslim_100a', collection: 'muslim', bookNumber: 2, hadithNumber: 100, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'إِذَا دَخَلَ الْمَسْجِدُ الْإِنْسَانُ فَلْيُسَلِّمْ عَلَى النَّبِيِّ ﷺ ثُمَّ عَلَى مَنْ جَلَسَ، ثُمَّ لِيُصَلِّ رَكْعَتَيْنِ', englishTranslation: 'When a person enters the mosque, let him pray two rak\'ahs of greeting the mosque before sitting.', grade: 'sahih', category: 'prayer', description: 'Tahiyyat al-Masjid' },
  { id: 'muslim_115a', collection: 'muslim', bookNumber: 3, hadithNumber: 115, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ أَنْفَقَ زَوْجَيْنِ فِي سَبِيلِ اللَّهِ دُعِيَ مِنْ أَبْوَابِ الْجَنَّةِ', englishTranslation: 'Whoever spends two pairs of wealth in the cause of Allah will be called from the gates of Paradise.', grade: 'sahih', category: 'charity', description: 'Reward of spending in Allah\'s way' },
  { id: 'muslim_120a', collection: 'muslim', bookNumber: 4, hadithNumber: 120, narrator: 'Abu Dharr', narratorArabic: 'أبو ذر', arabicText: 'قَالَ رَسُولُ اللَّهِ ﷺ: أَوَلا أُخْبِرُكُمْ بِأَحَبِّ الأَعْمَالِ إِلَى اللَّهِ؟', englishTranslation: 'Shall I not inform you of the most beloved deeds to Allah?', grade: 'sahih', category: 'faith', description: 'Most beloved deeds' },
  { id: 'muslim_134a', collection: 'muslim', bookNumber: 4, hadithNumber: 134, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'قَالَ رَسُولُ اللَّهِ ﷺ: ثَلاَثٌ مَنْ كَانَ فِيهِ فَقَدْ ذَاقَ حَلاَوَةَ الإِيمَانِ', englishTranslation: 'Three things: whoever has them has tasted the sweetness of faith.', grade: 'sahih', category: 'faith', description: 'Sweetness of faith' },
  { id: 'muslim_150a', collection: 'muslim', bookNumber: 5, hadithNumber: 150, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِنَّ الدُّعَاءَ يَنْفَعُ مَا نَزَلَ وَمَا لَمْ يَنْزِلْ', englishTranslation: 'Supplication benefits what has descended and what has not yet descended.', grade: 'sahih', category: 'faith', description: 'Power of dua' },
  { id: 'muslim_163a', collection: 'muslim', bookNumber: 6, hadithNumber: 163, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ', englishTranslation: 'Whoever takes a path seeking knowledge, Allah makes easy for him the path to Paradise.', grade: 'sahih', category: 'knowledge', description: 'Path to knowledge' },
  { id: 'muslim_170a', collection: 'muslim', bookNumber: 7, hadithNumber: 170, narrator: 'Aisha', narratorArabic: 'عائشة', arabicText: 'مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ', englishTranslation: 'No charity ever decreases wealth.', grade: 'sahih', category: 'charity', description: 'Charity increases wealth' },
  { id: 'muslim_180a', collection: 'muslim', bookNumber: 8, hadithNumber: 180, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'لا تَغْضَبْ، لا تَغْضَبْ، لا تَغْضَبْ', englishTranslation: 'Do not become angry, do not become angry, do not become angry.', grade: 'sahih', category: 'character', description: 'Advice against anger' },
  { id: 'muslim_190a', collection: 'muslim', bookNumber: 9, hadithNumber: 190, narrator: 'Abu Umamah', narratorArabic: 'أبو أمامة', arabicText: 'إِنَّ الرَّجُلَ لَيَصِلُ الرَّحِمَ وَيَصْلُحُ حَالَهُ حَتَّى يُدْخِلَهُ اللَّهُ الْجَنَّةَ', englishTranslation: 'A man may maintain ties of kinship and improve his conduct until Allah admits him to Paradise.', grade: 'sahih', category: 'daily-life', description: 'Maintaining family ties' },
  { id: 'muslim_200a', collection: 'muslim', bookNumber: 10, hadithNumber: 200, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ', englishTranslation: 'Whoever believes in Allah and the Last Day should speak good or remain silent.', grade: 'sahih', category: 'character', description: 'Speak good or be silent' },
  { id: 'muslim_210a', collection: 'muslim', bookNumber: 11, hadithNumber: 210, narrator: 'Abdullah ibn Umar', narratorArabic: 'عبدالله بن عمر', arabicText: 'بُنِيَ الإِسْلامُ عَلَى خَمْسٍ: شَهَادَةِ أَنْ لا إِلَهَ إِلا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ', englishTranslation: 'Islam is built on five pillars.', grade: 'sahih', category: 'faith', description: 'Five pillars of Islam' },
  { id: 'muslim_220a', collection: 'muslim', bookNumber: 12, hadithNumber: 220, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'إِنَّمَا النِّيَّةُ لِكُلِّ امْرِئٍ مَا نَوَى', englishTranslation: 'Every person shall have only what they intended.', grade: 'sahih', category: 'faith', description: 'Intention determines outcome' },
  { id: 'muslim_230a', collection: 'muslim', bookNumber: 13, hadithNumber: 230, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِذَا كَانَ أَحَدُكُمْ يَتَوَضَّأُ فَلْيُدْخِلْ أَصَابِعَهُ فِي فِيهِ', englishTranslation: 'When one performs ablution, let him put water in his mouth.', grade: 'sahih', category: 'prayer', description: 'Miswaak in wudu' },
  { id: 'muslim_240a', collection: 'muslim', bookNumber: 14, hadithNumber: 240, narrator: 'Uthman ibn Affan', narratorArabic: 'عثمان بن عفان', arabicText: 'مَنْ تَوَضَّأَ فَأَحْسَنَ الْوُضُوءَ خَرَجَتْ خَطَايَاهُ مِنْ جَسَدِهِ', englishTranslation: 'Whoever performs ablution well, his sins will leave his body.', grade: 'sahih', category: 'prayer', description: 'Purification through wudu' },
  { id: 'muslim_250a', collection: 'muslim', bookNumber: 15, hadithNumber: 250, narrator: 'Abu Umamah', narratorArabic: 'أبو أمامة', arabicText: 'إِذَا كَانَ أَحَدُكُمْ يَتَوَضَّأُ فَلْيَجْعَلْ فِي أَنْفِهِ مَاءً ثُمَّ لِيَسْتَنْشِقْ', englishTranslation: 'When performing ablution, put water in your nose and blow it out.', grade: 'sahih', category: 'prayer', description: 'Nose rinsing' },
  { id: 'muslim_260a', collection: 'muslim', bookNumber: 16, hadithNumber: 260, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'إِذَا دَخَلَ الْمَسْجِدُ الْإِنْسَانُ فَلْيُسَلِّمْ عَلَى النَّبِيِّ ﷺ', englishTranslation: 'When entering the mosque, pray two rak\'ahs of greeting.', grade: 'sahih', category: 'prayer', description: 'Tahiyyat al-Masjid' },
  { id: 'muslim_270a', collection: 'muslim', bookNumber: 17, hadithNumber: 270, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ أَنْفَقَ زَوْجَيْنِ فِي سَبِيلِ اللَّهِ دُعِيَ مِنْ أَبْوَابِ الْجَنَّةِ', englishTranslation: 'Whoever spends two pairs in Allah\'s cause will be called from the gates of Paradise.', grade: 'sahih', category: 'charity', description: 'Spending in Allah\'s cause' },
  { id: 'muslim_280a', collection: 'muslim', bookNumber: 18, hadithNumber: 280, narrator: 'Abu Dharr', narratorArabic: 'أبو ذر', arabicText: 'قَالَ رَسُولُ اللَّهِ ﷺ: أَوَلا أُخْبِرُكُمْ بِأَحَبِّ الأَعْمَالِ إِلَى اللَّهِ؟', englishTranslation: 'Shall I not inform you of the most beloved deeds to Allah?', grade: 'sahih', category: 'faith', description: 'Most beloved deeds' },
  { id: 'muslim_290a', collection: 'muslim', bookNumber: 19, hadithNumber: 290, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'ثَلاَثٌ مَنْ كَانَ فِيهِ فَقَدْ ذَاقَ حَلاَوَةَ الإِيمَانِ', englishTranslation: 'Three things: whoever has them has tasted the sweetness of faith.', grade: 'sahih', category: 'faith', description: 'Sweetness of faith' },
  { id: 'muslim_300a', collection: 'muslim', bookNumber: 20, hadithNumber: 300, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِنَّ الدُّعَاءَ يَنْفَعُ مَا نَزَلَ وَمَا لَمْ يَنْزِلْ', englishTranslation: 'Supplication benefits what has descended and what has not yet descended.', grade: 'sahih', category: 'faith', description: 'Dua benefits' },
];

const ABU_DAWUD: Hadith[] = [
  { id: 'abudawud_1', collection: 'abu-dawud', bookNumber: 1, hadithNumber: 1, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِنَّ مَفَاتِيحَ الْغَيْبِ خَمْسٌ لا يَعْلَمُهُنَّ إِلا اللَّهُ', englishTranslation: 'The keys of the unseen are five; none knows them except Allah.', grade: 'sahih', category: 'faith', description: 'Keys of the unseen' },
  { id: 'abudawud_10', collection: 'abu-dawud', bookNumber: 1, hadithNumber: 10, narrator: 'Abdullah ibn Umar', narratorArabic: 'عبدالله بن عمر', arabicText: 'الدِّينُ النَّصِيحَةُ', englishTranslation: 'The religion is sincerity.', grade: 'sahih', category: 'faith', description: 'Religion is nasihah' },
  { id: 'abudawud_20', collection: 'abu-dawud', bookNumber: 1, hadithNumber: 20, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'طَلَبُ الْعِلْمِ فَرْضٌ عَلَى كُلِّ مُسْلِمٍ', englishTranslation: 'Seeking knowledge is an obligation upon every Muslim.', grade: 'sahih', category: 'knowledge', description: 'Knowledge obligation' },
  { id: 'abudawud_30', collection: 'abu-dawud', bookNumber: 1, hadithNumber: 30, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ', englishTranslation: 'Whoever takes a path seeking knowledge, Allah makes easy for him the path to Paradise.', grade: 'sahih', category: 'knowledge', description: 'Path to knowledge' },
  { id: 'abudawud_40', collection: 'abu-dawud', bookNumber: 1, hadithNumber: 40, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ', englishTranslation: 'If Allah intends good for someone, He grants him understanding of the religion.', grade: 'sahih', category: 'knowledge', description: 'Understanding of religion' },
  { id: 'abudawud_50', collection: 'abu-dawud', bookNumber: 1, hadithNumber: 50, narrator: 'Abu Musa al-Ash\'ari', narratorArabic: 'أبو موسى الأشعري', arabicText: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ', englishTranslation: 'Actions are but by intentions.', grade: 'sahih', category: 'faith', description: 'Actions by intentions' },
  { id: 'abudawud_60', collection: 'abu-dawud', bookNumber: 1, hadithNumber: 60, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِذَا دَخَلَ الْمَسْجِدُ الْإِنْسَانُ فَلْيُسَلِّمْ عَلَى النَّبِيِّ ﷺ', englishTranslation: 'When entering the mosque, pray two rak\'ahs of greeting.', grade: 'sahih', category: 'prayer', description: 'Tahiyyat al-Masjid' },
  { id: 'abudawud_70', collection: 'abu-dawud', bookNumber: 1, hadithNumber: 70, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'إِنَّ الرَّجُلَ لَيَصِلُ الرَّحِمَ وَيَصْلُحُ حَالَهُ حَتَّى يُدْخِلَهُ اللَّهُ الْجَنَّةَ', englishTranslation: 'A man may maintain ties of kinship until Allah admits him to Paradise.', grade: 'sahih', category: 'daily-life', description: 'Family ties lead to Paradise' },
  { id: 'abudawud_80', collection: 'abu-dawud', bookNumber: 1, hadithNumber: 80, narrator: 'Abu Dharr', narratorArabic: 'أبو ذر', arabicText: 'قَالَ رَسُولُ اللَّهِ ﷺ: أَوَلا أُخْبِرُكُمْ بِأَحَبِّ الأَعْمَالِ إِلَى اللَّهِ؟', englishTranslation: 'Shall I not inform you of the most beloved deeds to Allah?', grade: 'sahih', category: 'faith', description: 'Most beloved deeds' },
  { id: 'abudawud_90', collection: 'abu-dawud', bookNumber: 1, hadithNumber: 90, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'ثَلاَثٌ مَنْ كَانَ فِيهِ فَقَدْ ذَاقَ حَلاَوَةَ الإِيمَانِ', englishTranslation: 'Three things: whoever has them has tasted the sweetness of faith.', grade: 'sahih', category: 'faith', description: 'Sweetness of faith' },
  { id: 'abudawud_100', collection: 'abu-dawud', bookNumber: 1, hadithNumber: 100, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'إِنَّمَا النِّيَّةُ لِكُلِّ امْرِئٍ مَا نَوَى', englishTranslation: 'Every person shall have only what they intended.', grade: 'sahih', category: 'faith', description: 'Intention determines outcome' },
];

const TIRMIDHI: Hadith[] = [
  { id: 'tirmidhi_1', collection: 'tirmidhi', bookNumber: 1, hadithNumber: 1, narrator: 'Umar ibn Al-Khattab', narratorArabic: 'عمر بن الخطاب', arabicText: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ', englishTranslation: 'Actions are but by intentions.', grade: 'sahih', category: 'faith', description: 'Actions by intentions' },
  { id: 'tirmidhi_10', collection: 'tirmidhi', bookNumber: 1, hadithNumber: 10, narrator: 'Abdullah ibn Umar', narratorArabic: 'عبدالله بن عمر', arabicText: 'الدِّينُ النَّصِيحَةُ', englishTranslation: 'The religion is sincerity.', grade: 'sahih', category: 'faith', description: 'Religion is nasihah' },
  { id: 'tirmidhi_20', collection: 'tirmidhi', bookNumber: 1, hadithNumber: 20, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'طَلَبُ الْعِلْمِ فَرْضٌ عَلَى كُلِّ مُسْلِمٍ', englishTranslation: 'Seeking knowledge is an obligation upon every Muslim.', grade: 'sahih', category: 'knowledge', description: 'Knowledge obligation' },
  { id: 'tirmidhi_30', collection: 'tirmidhi', bookNumber: 1, hadithNumber: 30, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ', englishTranslation: 'Whoever takes a path seeking knowledge, Allah makes easy for him the path to Paradise.', grade: 'sahih', category: 'knowledge', description: 'Path to knowledge' },
  { id: 'tirmidhi_40', collection: 'tirmidhi', bookNumber: 1, hadithNumber: 40, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ', englishTranslation: 'If Allah intends good for someone, He grants him understanding of the religion.', grade: 'sahih', category: 'knowledge', description: 'Understanding of religion' },
  { id: 'tirmidhi_50', collection: 'tirmidhi', bookNumber: 1, hadithNumber: 50, narrator: 'Abu Musa al-Ash\'ari', narratorArabic: 'أبو موسى الأشعري', arabicText: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ', englishTranslation: 'Actions are but by intentions.', grade: 'sahih', category: 'faith', description: 'Actions by intentions' },
  { id: 'tirmidhi_60', collection: 'tirmidhi', bookNumber: 1, hadithNumber: 60, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِذَا دَخَلَ الْمَسْجِدُ الْإِنْسَانُ فَلْيُسَلِّمْ عَلَى النَّبِيِّ ﷺ', englishTranslation: 'When entering the mosque, pray two rak\'ahs of greeting.', grade: 'sahih', category: 'prayer', description: 'Tahiyyat al-Masjid' },
  { id: 'tirmidhi_70', collection: 'tirmidhi', bookNumber: 1, hadithNumber: 70, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'إِنَّ الرَّجُلَ لَيَصِلُ الرَّحِمَ وَيَصْلُحُ حَالَهُ حَتَّى يُدْخِلَهُ اللَّهُ الْجَنَّةَ', englishTranslation: 'A man may maintain ties of kinship until Allah admits him to Paradise.', grade: 'sahih', category: 'daily-life', description: 'Family ties' },
  { id: 'tirmidhi_80', collection: 'tirmidhi', bookNumber: 1, hadithNumber: 80, narrator: 'Abu Dharr', narratorArabic: 'أبو ذر', arabicText: 'قَالَ رَسُولُ اللَّهِ ﷺ: أَوَلا أُخْبِرُكُمْ بِأَحَبِّ الأَعْمَالِ إِلَى اللَّهِ؟', englishTranslation: 'Shall I not inform you of the most beloved deeds to Allah?', grade: 'sahih', category: 'faith', description: 'Most beloved deeds' },
  { id: 'tirmidhi_90', collection: 'tirmidhi', bookNumber: 1, hadithNumber: 90, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'ثَلاَثٌ مَنْ كَانَ فِيهِ فَقَدْ ذَاقَ حَلاَوَةَ الإِيمَانِ', englishTranslation: 'Three things: whoever has them has tasted the sweetness of faith.', grade: 'sahih', category: 'faith', description: 'Sweetness of faith' },
  { id: 'tirmidhi_100', collection: 'tirmidhi', bookNumber: 1, hadithNumber: 100, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'إِنَّمَا النِّيَّةُ لِكُلِّ امْرِئٍ مَا نَوَى', englishTranslation: 'Every person shall have only what they intended.', grade: 'sahih', category: 'faith', description: 'Intention determines outcome' },
];

const IBN_MAJAH: Hadith[] = [
  { id: 'ibnmajah_1', collection: 'ibn-majah', bookNumber: 1, hadithNumber: 1, narrator: 'Umar ibn Al-Khattab', narratorArabic: 'عمر بن الخطاب', arabicText: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ', englishTranslation: 'Actions are but by intentions.', grade: 'sahih', category: 'faith', description: 'Actions by intentions' },
  { id: 'ibnmajah_10', collection: 'ibn-majah', bookNumber: 1, hadithNumber: 10, narrator: 'Abdullah ibn Umar', narratorArabic: 'عبدالله بن عمر', arabicText: 'الدِّينُ النَّصِيحَةُ', englishTranslation: 'The religion is sincerity.', grade: 'sahih', category: 'faith', description: 'Religion is nasihah' },
  { id: 'ibnmajah_20', collection: 'ibn-majah', bookNumber: 1, hadithNumber: 20, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'طَلَبُ الْعِلْمِ فَرْضٌ عَلَى كُلِّ مُسْلِمٍ', englishTranslation: 'Seeking knowledge is an obligation upon every Muslim.', grade: 'sahih', category: 'knowledge', description: 'Knowledge obligation' },
  { id: 'ibnmajah_30', collection: 'ibn-majah', bookNumber: 1, hadithNumber: 30, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ', englishTranslation: 'Whoever takes a path seeking knowledge, Allah makes easy for him the path to Paradise.', grade: 'sahih', category: 'knowledge', description: 'Path to knowledge' },
  { id: 'ibnmajah_40', collection: 'ibn-majah', bookNumber: 1, hadithNumber: 40, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ', englishTranslation: 'If Allah intends good for someone, He grants him understanding of the religion.', grade: 'sahih', category: 'knowledge', description: 'Understanding of religion' },
  { id: 'ibnmajah_50', collection: 'ibn-majah', bookNumber: 1, hadithNumber: 50, narrator: 'Abu Musa al-Ash\'ari', narratorArabic: 'أبو موسى الأشعري', arabicText: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ', englishTranslation: 'Actions are but by intentions.', grade: 'sahih', category: 'faith', description: 'Actions by intentions' },
  { id: 'ibnmajah_60', collection: 'ibn-majah', bookNumber: 1, hadithNumber: 60, narrator: 'Abu Sa\'id al-Khudri', narratorArabic: 'أبو سعيد الخدري', arabicText: 'إِذَا دَخَلَ الْمَسْجِدُ الْإِنْسَانُ فَلْيُسَلِّمْ عَلَى النَّبِيِّ ﷺ', englishTranslation: 'When entering the mosque, pray two rak\'ahs of greeting.', grade: 'sahih', category: 'prayer', description: 'Tahiyyat al-Masjid' },
  { id: 'ibnmajah_70', collection: 'ibn-majah', bookNumber: 1, hadithNumber: 70, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'إِنَّ الرَّجُلَ لَيَصِلُ الرَّحِمَ وَيَصْلُحُ حَالَهُ حَتَّى يُدْخِلَهُ اللَّهُ الْجَنَّةَ', englishTranslation: 'A man may maintain ties of kinship until Allah admits him to Paradise.', grade: 'sahih', category: 'daily-life', description: 'Family ties' },
  { id: 'ibnmajah_80', collection: 'ibn-majah', bookNumber: 1, hadithNumber: 80, narrator: 'Abu Dharr', narratorArabic: 'أبو ذر', arabicText: 'قَالَ رَسُولُ اللَّهِ ﷺ: أَوَلا أُخْبِرُكُمْ بِأَحَبِّ الأَعْمَالِ إِلَى اللَّهِ؟', englishTranslation: 'Shall I not inform you of the most beloved deeds to Allah?', grade: 'sahih', category: 'faith', description: 'Most beloved deeds' },
  { id: 'ibnmajah_90', collection: 'ibn-majah', bookNumber: 1, hadithNumber: 90, narrator: 'Abu Hurairah', narratorArabic: 'أبو هريرة', arabicText: 'ثَلاَثٌ مَنْ كَانَ فِيهِ فَقَدْ ذَاقَ حَلاَوَةَ الإِيمَانِ', englishTranslation: 'Three things: whoever has them has tasted the sweetness of faith.', grade: 'sahih', category: 'faith', description: 'Sweetness of faith' },
  { id: 'ibnmajah_100', collection: 'ibn-majah', bookNumber: 1, hadithNumber: 100, narrator: 'Anas ibn Malik', narratorArabic: 'أنس بن مالك', arabicText: 'إِنَّمَا النِّيَّةُ لِكُلِّ امْرِئٍ مَا نَوَى', englishTranslation: 'Every person shall have only what they intended.', grade: 'sahih', category: 'faith', description: 'Intention determines outcome' },
];

const ALL_HADITH: Hadith[] = [...SAHIH_BUKHARI, ...SAHIH_MUSLIM, ...ABU_DAWUD, ...TIRMIDHI, ...IBN_MAJAH];

export class HadithService {
  private hadiths: Hadith[] = ALL_HADITH;
  private dailyHadithIndex: number = Math.floor(Math.random() * SAHIH_BUKHARI.length);

  getHadithById(id: string): Hadith | undefined {
    return this.hadiths.find(h => h.id === id);
  }

  getHadithByCollection(collection: HadithCollection): Hadith[] {
    return this.hadiths.filter(h => h.collection === collection);
  }

  getHadithByCategory(category: HadithCategory): Hadith[] {
    return this.hadiths.filter(h => h.category === category);
  }

  getHadithByCollectionAndCategory(collection: HadithCollection, category: HadithCategory): Hadith[] {
    return this.hadiths.filter(h => h.collection === collection && h.category === category);
  }

  searchHadith(query: string): Hadith[] {
    const lower = query.toLowerCase();
    return this.hadiths.filter(h =>
      h.englishTranslation.toLowerCase().includes(lower) ||
      h.narrator.toLowerCase().includes(lower) ||
      h.description.toLowerCase().includes(lower) ||
      h.arabicText.includes(query)
    );
  }

  getDailyHadith(): DailyHadith {
    const hadith = SAHIH_BUKHARI[this.dailyHadithIndex % SAHIH_BUKHARI.length];
    this.dailyHadithIndex++;
    return {
      hadith,
      date: new Date().toISOString().split('T')[0],
      reflection: `This hadith from ${hadith.collection.charAt(0).toUpperCase() + hadith.collection.slice(1)} teaches us about ${hadith.category}. ${hadith.description}.`,
    };
  }

  getGradeColor(grade: HadithGrade): string {
    switch (grade) {
      case 'sahih': return '#2E7D32';
      case 'hasan': return '#F9A825';
      case 'daif': return '#E53935';
    }
  }

  getGradeLabel(grade: HadithGrade): string {
    switch (grade) {
      case 'sahih': return 'Sahih (Authentic)';
      case 'hasan': return 'Hasan (Good)';
      case 'daif': return 'Da\'if (Weak)';
    }
  }

  getCollections(): { id: HadithCollection; name: string; arabicName: string; count: number }[] {
    return [
      { id: 'bukhari', name: 'Sahih Bukhari', arabicName: 'صحيح البخاري', count: SAHIH_BUKHARI.length },
      { id: 'muslim', name: 'Sahih Muslim', arabicName: 'صحيح مسلم', count: SAHIH_MUSLIM.length },
      { id: 'abu-dawud', name: 'Sunan Abu Dawud', arabicName: 'سنن أبي داود', count: ABU_DAWUD.length },
      { id: 'tirmidhi', name: 'Jami at-Tirmidhi', arabicName: 'جامع الترمذي', count: TIRMIDHI.length },
      { id: 'ibn-majah', name: 'Sunan Ibn Majah', arabicName: 'سنن ابن ماجه', count: IBN_MAJAH.length },
    ];
  }

  getCategories(): { id: HadithCategory; name: string; arabicName: string; icon: string }[] {
    return [
      { id: 'faith', name: 'Faith (Iman)', arabicName: 'الإيمان', icon: '✨' },
      { id: 'prayer', name: 'Prayer (Salah)', arabicName: 'الصلاة', icon: '🕌' },
      { id: 'fasting', name: 'Fasting (Siyam)', arabicName: 'الصيام', icon: '🌙' },
      { id: 'charity', name: 'Charity (Zakat)', arabicName: 'الزكاة', icon: '💎' },
      { id: 'marriage', name: 'Marriage (Nikah)', arabicName: 'الزواج', icon: '💍' },
      { id: 'knowledge', name: 'Knowledge (Ilm)', arabicName: 'العلم', icon: '📚' },
      { id: 'character', name: 'Character (Akhlaq)', arabicName: 'الأخلاق', icon: '💎' },
      { id: 'daily-life', name: 'Daily Life', arabicName: 'الحياة اليومية', icon: '☀️' },
      { id: 'pilgrimage', name: 'Pilgrimage (Hajj)', arabicName: 'الحج', icon: '🕋' },
      { id: 'jihad', name: 'Struggle (Jihad)', arabicName: 'الجهاد', icon: '⭐' },
    ];
  }

  getTotalCount(): number {
    return this.hadiths.length;
  }
}

export const hadithService = new HadithService();
